import { Language } from "../models/model";

// languages.ts
export const allLanguages: Language[] = [
    { englishName: "Afrikaans", displayName: "Afrikaans", isocode: "af" },
    { englishName: "Albanian", displayName: "Shqip", isocode: "sq" },
    { englishName: "Amharic", displayName: "አማርኛ", isocode: "am" },
    { englishName: "Arabic", displayName: "العربية", isocode: "ar" },
    { englishName: "Armenian", displayName: "Հայերեն", isocode: "hy" },
    { englishName: "Azerbaijani", displayName: "Azərbaycanca", isocode: "az" },
    { englishName: "Basque", displayName: "Euskara", isocode: "eu" },
    { englishName: "Belarusian", displayName: "Беларуская", isocode: "be" },
    { englishName: "Bengali", displayName: "বাংলা", isocode: "bn" },
    { englishName: "Bosnian", displayName: "Bosanski", isocode: "bs" },
    { englishName: "Bulgarian", displayName: "Български", isocode: "bg" },
    { englishName: "Burmese", displayName: "မြန်မာ", isocode: "my" },
    { englishName: "Catalan", displayName: "Català", isocode: "ca" },
    { englishName: "Chinese", displayName: "中文", isocode: "zh" },
    { englishName: "Croatian", displayName: "Hrvatski", isocode: "hr" },
    { englishName: "Czech", displayName: "Čeština", isocode: "cs" },
    { englishName: "Danish", displayName: "Dansk", isocode: "da" },
    { englishName: "Dutch", displayName: "Nederlands", isocode: "nl" },
    { englishName: "English", displayName: "English", isocode: "en" },
    { englishName: "Estonian", displayName: "Eesti", isocode: "et" },
    { englishName: "Finnish", displayName: "Suomi", isocode: "fi" },
    { englishName: "French", displayName: "Français", isocode: "fr" },
    { englishName: "Georgian", displayName: "ქართული", isocode: "ka" },
    { englishName: "German", displayName: "Deutsch", isocode: "de" },
    { englishName: "Greek", displayName: "Ελληνικά", isocode: "el" },
    { englishName: "Gujarati", displayName: "ગુજરાતી", isocode: "gu" },
    { englishName: "Hebrew", displayName: "עברית", isocode: "he" },
    { englishName: "Hindi", displayName: "हिन्दी", isocode: "hi" },
    { englishName: "Hungarian", displayName: "Magyar", isocode: "hu" },
    { englishName: "Icelandic", displayName: "Íslenska", isocode: "is" },
    { englishName: "Indonesian", displayName: "Bahasa Indonesia", isocode: "id" },
    { englishName: "Italian", displayName: "Italiano", isocode: "it" },
    { englishName: "Japanese", displayName: "日本語", isocode: "ja" },
    { englishName: "Kannada", displayName: "ಕನ್ನಡ", isocode: "kn" },
    { englishName: "Kazakh", displayName: "Қазақша", isocode: "kk" },
    { englishName: "Khmer", displayName: "ភាសាខ្មែរ", isocode: "km" },
    { englishName: "Korean", displayName: "한국어", isocode: "ko" },
    { englishName: "Lao", displayName: "ພາສາລາວ", isocode: "lo" },
    { englishName: "Latvian", displayName: "Latviešu", isocode: "lv" },
    { englishName: "Lithuanian", displayName: "Lietuvių", isocode: "lt" },
    { englishName: "Macedonian", displayName: "Македонски", isocode: "mk" },
    { englishName: "Malay", displayName: "Bahasa Melayu", isocode: "ms" },
    { englishName: "Malayalam", displayName: "മലയാളം", isocode: "ml" },
    { englishName: "Maltese", displayName: "Malti", isocode: "mt" },
    { englishName: "Marathi", displayName: "मराठी", isocode: "mr" },
    { englishName: "Mongolian", displayName: "Монгол", isocode: "mn" },
    { englishName: "Nepali", displayName: "नेपाली", isocode: "ne" },
    { englishName: "Norwegian", displayName: "Norsk", isocode: "no" },
    { englishName: "Persian", displayName: "فارسی", isocode: "fa" },
    { englishName: "Polish", displayName: "Polski", isocode: "pl" },
    { englishName: "Portuguese", displayName: "Português", isocode: "pt" },
    { englishName: "Punjabi", displayName: "ਪੰਜਾਬੀ", isocode: "pa" },
    { englishName: "Romanian", displayName: "Română", isocode: "ro" },
    { englishName: "Russian", displayName: "Русский", isocode: "ru" },
    { englishName: "Serbian", displayName: "Српски", isocode: "sr" },
    { englishName: "Sinhala", displayName: "සිංහල", isocode: "si" },
    { englishName: "Slovak", displayName: "Slovenčina", isocode: "sk" },
    { englishName: "Slovenian", displayName: "Slovenščina", isocode: "sl" },
    { englishName: "Spanish", displayName: "Español", isocode: "es" },
    { englishName: "Swedish", displayName: "Svenska", isocode: "sv" },
    { englishName: "Tamil", displayName: "தமிழ்", isocode: "ta" },
    { englishName: "Telugu", displayName: "తెలుగు", isocode: "te" },
    { englishName: "Thai", displayName: "ไทย", isocode: "th" },
    { englishName: "Turkish", displayName: "Türkçe", isocode: "tr" },
    { englishName: "Ukrainian", displayName: "Українська", isocode: "uk" },
    { englishName: "Urdu", displayName: "اردو", isocode: "ur" },
    { englishName: "Vietnamese", displayName: "Tiếng Việt", isocode: "vi" },
    { englishName: "Zulu", displayName: "IsiZulu", isocode: "zu" }
  ];
  